# Generated by Django 5.0.2 on 2024-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
