# Generated by Django 5.0.2 on 2024-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_event_total_tickets_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='images/', max_length=255, null=True, upload_to=''),
        ),
    ]
