# Generated by Django 5.0.2 on 2024-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_path',
            field=models.ImageField(default='images/default.jpg', max_length=255, upload_to=''),
        ),
    ]
